# Generated by Django 5.2.4 on 2025-10-28 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(max_length=100)),
                ("sender_email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Hizmet Başlığı"),
                ),
                (
                    "short_description",
                    models.CharField(max_length=255, verbose_name="Kısa Açıklama"),
                ),
                ("description", models.TextField()),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Örn: cloud, mobile, gear (Frontend ikon adı)",
                        max_length=50,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Anasayfada Öne Çıksın mı?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hizmet",
                "verbose_name_plural": "Hizmetler",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad Soyad")),
                ("role", models.CharField(max_length=100, verbose_name="Pozisyon")),
                (
                    "bio",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kısa Biyografi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ekip Üyesi",
                "verbose_name_plural": "Ekip Üyeleri",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Makale Başlığı"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL Slugı"
                    ),
                ),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "published_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Yayınlandı mı?"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.teammember",
                        verbose_name="Yazar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Makale",
                "verbose_name_plural": "Makaleler",
                "ordering": ["-published_date"],
            },
        ),
    ]
