# Generated by Django 5.2.4 on 2025-10-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Services",
            new_name="Service",
        ),
    ]
